'use strict';

let _ = require('lodash');
let fs = require('fs');
let path = require('path');
let async = require('async');
let json2csv = require('json2csv');

if (!process.argv || process.argv.length < 3) {
  console.log('Vizabi csv files will be generated by default, cause file with schemas was not provided as an argument.');
}

if (process.argv.length > 3) {
  console.log('Only first given file path will be used by data generatior');
}

let request = require('request-json');

const WS_URL = process.env.WS_URL || 'http://localhost:3000';
let client = request.createClient(WS_URL);

let endpoints = {
  geos: {
    path: '/api/geo/countries',
    preProcessData: data => {
      return _.chain(data.rows)
        .map(row => _.zipObject(data.headers, _.map(row, replaceNullWithUndefined)))
        .value();
    }
  },
  measureValues: {
    path: '/api/graphs/stats/vizabi-tools',
    preProcessData: data => {
      return _.chain(data.rows)
        .sortBy('0')
        .sortBy('1')
        .map(row => _.zipObject(data.headers, _.map(row, replaceNullWithUndefined)))
        .value();
    }
  }
};

let generationSchemaFile = process.argv[2];
let generationSchemas = generationSchemaFile ? require(path.resolve(__dirname, generationSchemaFile)) : require('./vizabiCsvSchemas');

let generationTasks = _.map(generationSchemas, schema => {
  return cb => {
    async.waterfall([
      cb => client.get(createUrl(schema), (err, res, body) =>  cb(err, body)),
      (docs, cb) => generateCsv(schema, docs, cb),
      (csv, cb) => fs.writeFile(schema.file, csv, 'utf8', cb)
    ], (error) => {
      if (error) {
        console.error(error);
      }
      console.log(`Completed generating ${schema.file}`);
      return cb(error);
    });
  }
});

async.parallelLimit(generationTasks, 10, error => {
  if (error) {
    console.error(error);
  }

  console.log('All generation tasks were completed');
  process.exit(0);
});

function replaceNullWithUndefined(value) {
  return value === null ? undefined : value;
}

function createUrl(schema) {
  let urlPath = endpoints[schema.endpoint].path;
  if (!schema.query) return urlPath;

  return `${urlPath}?${schema.query}`;
}

function generateCsv(schema, data, cb) {
  let doNothingWithData = data => data;

  let preProcessData = endpoints[schema.endpoint].preProcessData || doNothingWithData;
  return json2csv({
    fields: schema.wsProperties,
    fieldNames: schema.headers,
    data: preProcessData(data),
    quotes: '"'
  }, cb);
}
