[template]
src = "haproxy.tmpl"
dest = "/etc/haproxy/haproxy.cfg"
owner = "haproxy"
mode = "0644"
keys = [
  "/upstreams"
]
check_cmd = "/usr/sbin/haproxy -c -f {{.src}}"
reload_cmd = "./haproxy_gracefull_reload.sh"
